[tool.poetry]
name = "wells"
version = "0.1.0"
description = "Manage well logs with S3, DynamoDB, and AWS Lambda"
authors = ["Don Fox <don@thedataincubator.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ImageHash = "4.3.1"
boto3 = "1.34.128"


[tool.poetry.group.dev.dependencies]
pytest = "8.2.2"
flake8 = "7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[flake8]
max-line-length = 88

[tool.pytest.ini_options]
markers = ["integration: Integration tests"]
